### ISSUE TITLE
Add password protection to staging site

### ISSUE THREAD

**Issue by joshrounsville** [helpsupply/helpsupply#100]
This may not be possible based on a cursory search, but deserves some research. A minimal fallback may be using robots.txt to prevent the site from being indexed.

**Comment by WesSouza** [comment]
Given this project is open, do we need to protect the staging environment?

I'd propose adding some visual cue indicating it's the staging environment, something like a banner on top.

**Comment by joshrounsville** [comment]
@WesSouza good question and Idea. Does anyone else have a take on the need to protect the staging site? 

CC: @newhouseb @johnsonfung @izgeorge @lizbanach @tricia-work @davydka

**Comment by newhouseb** [comment]
I see no reason to, given that it's open source and we're not importing any data from production.

**Comment by joshrounsville** [comment]
Great, thanks @newhouseb! I'll close this issue.
