### ISSUE TITLE
Start page: implement desktop design

### ISSUE THREAD

**Issue by tricia-work** [helpsupply/helpsupply#113]
<img width="680" alt="Screen Shot 2020-03-28 at 10 38 52 PM" src="https://user-images.githubusercontent.com/49690261/77842245-eca25d80-7144-11ea-9888-c62c3645ce9f.png">

**Comment by newhouseb** [comment]
@tricia-work this looks :fire:, but when on my (normal sized) laptop screen I can't scroll on pages with long forms (i.e. https://help-supply-staging.web.app/dropsite/new/admin/)

**Comment by tricia-work** [comment]
Thanks for reporting @newhouseb! One of us from Work & Co team will be looking into this as soon as possible.
