### ISSUE TITLE
Setup staging environment

### ISSUE THREAD

**Issue by lizbanach** [helpsupply/helpsupply#60]

**Comment by newhouseb** [comment]
@lizbanach this includes a live site, right? do you think it's be a problem if the local dev environments and the staging environment share the same database? (otherwise, we can set up a third firebase copy)

**Comment by lizbanach** [comment]
@newhouseb it would be awesome if we could have a live staging env! especially since i believe we are having qa join soon

**Comment by joshrounsville** [comment]
@newhouseb I think we will be fine to share a database for local dev and the staging environment. @lizbanach @WesSouza do you see any issues with that?
